### ISSUE TITLE
Parámetros de evento

### ISSUE THREAD

**Issue by fergpichel** [AlfredoPombo/PruebaSelect#2]
`diámetroSeleccionado(event){ }`

Aquí mira que trae `event` e se non trae o `item` podes probar a pasarllo ti:

`@tap="diámetroSeleccionado(item)"`

**Consellos:**
- Os nomes de funcións representan accións, é mellor que uses un verbo: `seleccionarDiametro`
- Os condicionales encargados de mostrar/ocultar, cando como en este caso, hai elementos dependientes, podes aforrar unha variable. Se queres mostrar o listado e ocultar o botón, podes usar 1 sola variable así  `v-show="!mostrarBoton"` (a exclamación significa negación) (Recorda que canto menos código, máis fácil de manter no tempo)

**Comment by AlfredoPombo** [comment]
Sigue sin funcionar...
